"""Deterministic config-file generators for the Lampy stack.

Every generator is a pure function: same inputs -> same bytes, no timestamps,
no randomness, no host-dependent values. Generated files carry a header
naming the generator and inputs so drift is detectable by diff.
"""
from __future__ import annotations

HEADER = "# Generated by lampy.config_gen.{func} — do not hand-edit.\n"


def apache_vhost(server_name: str = "localhost",
                 docroot: str = r"C:\Lampy\xapp\static",
                 xapp_port: int = 8000,
                 server_admin: str = "admin@localhost") -> str:
    """Apache HTTPD virtual host: serves static files, proxies /api to xapp."""
    body = f"""ServerName {server_name}
ServerAdmin {server_admin}

DocumentRoot "{docroot}"
<Directory "{docroot}">
    Require all granted
</Directory>

ProxyPreserveHost On
ProxyPass /api/ http://127.0.0.1:{xapp_port}/api/
ProxyPassReverse /api/ http://127.0.0.1:{xapp_port}/api/

ErrorLog "logs/lampy-error.log"
CustomLog "logs/lampy-access.log" common
"""
    return HEADER.format(func="apache_vhost") + body


def ollama_env(models_dir: str = r"C:\Lampy\data\ollama",
               host: str = "127.0.0.1:11434",
               keep_alive: str = "5m") -> str:
    """Environment file consumed by the Ollama service wrapper on Windows."""
    lines = [
        HEADER.format(func="ollama_env").rstrip("\n"),
        f"OLLAMA_MODELS={models_dir}",
        f"OLLAMA_HOST={host}",
        f"OLLAMA_KEEP_ALIVE={keep_alive}",
        "",
    ]
    return "\n".join(lines)


def james_ports_remap() -> str:
    """Documents the James port remapping (host-clash avoidance).

    James defaults -> Lampy remapped:
      smtp  25 -> 2525    smtps 465 -> 2465    submission 587 -> 2587
      imap 143 -> 1143    imaps 993 -> 1993    pop3 110 -> 1110
    """
    return HEADER.format(func="james_ports_remap") + (
        "smtp=2525\nsmtps=2465\nsubmission=2587\n"
        "imap=1143\nimaps=1993\npop3=1110\n"
    )


def write(path: str, content: str) -> str:
    """Write *content* to *path* (creating parents); return the path."""
    import os
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    return path
